(let [s @infra.dev.window.lifecycle/service-state w @(:world s) cfg @(:config s)
      observer @(ns-resolve 'user 'truth-hardware-frame-observer)
      recorded @(:state observer)]
  (assert (= 4070721 (.pid (java.lang.ProcessHandle/current))))
  (assert (= 275227937 (System/identityHashCode (:world s))))
  (assert (= 129843170276688 (:window s)))
  (assert (> (:tick w) 4371))
  (assert (and (.isAlive ^Thread (:thread s)) (.isAlive ^Thread (:sim-thread s))))
  (assert (and (false? (:active? recorded))
               (:original-root-restored? recorded)
               (identical? @(:scene-var observer) (:original-scene observer))))
  (prn {:pid (.pid (java.lang.ProcessHandle/current))
        :world-atom-identity (System/identityHashCode (:world s)) :window (:window s)
        :render-worker-alive (.isAlive ^Thread (:thread s))
        :sim-worker-alive (.isAlive ^Thread (:sim-thread s))
        :service-error (some-> (:error s) str) :ui-error (some-> (:ui/error-state cfg) str)
        :world (select-keys w [:tick :genesis/sim-time :arc/current :demo/scenario :demo/fixture?])
        :states (frequencies (vals (get-in w [:components domain.ecs.components/matter-state])))
        :observer (select-keys recorded [:phase :active? :capture-attempts :errors :original-root-restored?])
        :scene-root-identical? (identical? @(:scene-var observer) (:original-scene observer))}))
