(ns domain.ecology.system
  "ECS integration: adoption, tick scheduling, and phase-event emission."
  (:require
   [domain.ecs.core :as ecs]
   [domain.ecs.components :as c]
   [domain.ecs.event :as event]
   [law.ecology :as le]
   [domain.ecology.state :as state]))

(defn- temp->01 "Map a surface temperature (K) into the ecology's [0,1] temp scale: 150 K → 0,\n   300 K → 0.5, 450 K → 1. The habitable band (0.25, 0.75) then spans 225–375 K,\n   bracketing liquid water." [t-kelvin] (max 0.0 (min 1.0 (/ (- (double (or t-kelvin 150.0)) 150.0) 300.0))))

(defn- moisture-from-composition "Initial moisture from a body's volatile inventory.\n   With explicit element composition, H + O proxy water/ice; legacy keys\n   (:H2O, :volatiles, :ices) are still counted if present." [composition] (let [w (+ (double (get composition :H2O 0.0)) (double (get composition :volatiles 0.0)) (double (get composition :ices 0.0)) (double (get composition :H 0.0)) (double (get composition :O 0.0)))] (max 0.0 (min 1.0 (+ 0.05 (* 2.5 w))))))

(defn adopt-ecology "A fresh abiotic ecology for a planet, initialised from its physical state." [world eid] (state/make-ecology {:temp (temp->01 (ecs/get-component world eid c/temperature)), :moisture (moisture-from-composition (or (ecs/get-component world eid c/composition) {}))}))

(defn- planet-habitable? "Gate for adopting an ecology: the body sits in the ecology's own habitable\n   temperature band (225–375 K via `temp->01`) AND carries enough water to seed\n   prebiotic chemistry. Uses the SAME band the ecology dynamics run on, so a\n   world that would sustain life can also start it — the previous gate keyed on\n   `chemistry/habitability-score > 0.2`, which required 273–373 K plus a surface\n   pressure and so excluded temperate, pressureless seed worlds. Kept independent\n   of domain.habitability to avoid a require cycle through domain.genesis." [world eid] (and (state/habitable? {:temp (temp->01 (ecs/get-component world eid c/temperature))}) (> (moisture-from-composition (or (ecs/get-component world eid c/composition) {})) 0.1)))

(def ^{:const true} ecology-interval-ticks "Physics ticks between ecology updates — the biosphere breathes on a slower\n   cadence than the integrator (~0.4 s of real time at the fixed 60 Hz rate,\n   per player-abilities-and-ecology.md §5)." 24)

(defn ecology-system "Write-set system: SOLE writer of c/ecology.\n\n   Every `ecology-interval-ticks`: habitable :planet bodies without an ecology\n   adopt a fresh abiotic one (initialised from their temperature/volatiles);\n   bodies with an ecology advance it one tick (passive dynamics, autonomous\n   chemistry, phase transitions, extinction). Transition EVENTS are emitted\n   separately by `emit-phase-events` in the tick driver — a fan-out system\n   only writes its component." [] {:id :ecology, :writes #{c/ecology}, :run (fn [world] (let [tick (long (or (:tick world) 0))] (if-not (zero? (mod tick ecology-interval-ticks)) {} (let [planets (ecs/entities-with world c/matter-state c/mass c/temperature) cell (into {} (keep (fn [eid] (let [eco (ecs/get-component world eid c/ecology)] (cond eco [eid (first (state/tick-ecology eco tick eid))] (and (= :planet (ecs/get-component world eid c/matter-state)) (planet-habitable? world eid)) [eid (adopt-ecology world eid)] :else nil)))) planets)] (if (empty? cell) {} {c/ecology cell})))))})

(defn emit-phase-events "Diff ecology phases between `prev-world` and `world` and dispatch the\n   corresponding ledger events: crossing into a living phase for the FIRST time\n   fires :event/life-emergence (the witnessing reward the arc/player layer\n   already prices); other advances fire :event/ecology-phase-transition; a\n   collapse back to :abiotic fires :event/ecology-extinction. Runs post-physics\n   in the tick driver, where the ledger is writable. Pure: world → world'." [world prev-world] (let [cur (get-in world [:components c/ecology] {}) prev (get-in prev-world [:components c/ecology] {}) tick (:tick world)] (reduce-kv (fn [w eid eco] (let [p-phase (:phase (get prev eid)) c-phase (:phase eco)] (if (or (nil? p-phase) (= p-phase c-phase)) w (let [was-living? (not (#{le/phase-abiotic le/phase-prebiotic} p-phase)) now-living? (state/living? eco) ever-lived? (some (fn* [p1__243#] (not (#{le/phase-abiotic le/phase-prebiotic} (:phase p1__243#)))) (butlast (:record eco))) kind (cond (and now-living? (not was-living?) (not ever-lived?)) :event/life-emergence (= c-phase le/phase-abiotic) :event/ecology-extinction :else :event/ecology-phase-transition)] (event/dispatch w (event/->event {:tick tick, :kind kind, :entities #{eid}, :payload {:from p-phase, :to c-phase}})))))) world cur)))
